# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  issue_comment:
    types: [ created ]

jobs:
  sendMessage:
    runs-on: ubuntu-latest

    steps:
      - name: send telegram message on comment opened
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: 6113203571:AAF1RKX5MaFfiihjvZb_AyiesoHl5vTCff8
          message: |
            From: ${{ github.event.sender.login }}
            Title: ${{ github.event.issue.title }}
            Link: ${{ github.event.repository.url }}
            Body:
            ${{ github.event.comment.body }}
            Link: ${{ github.event.action }}
